
input NewPostFile {
  type: String,
  uri: String,
}

input NewPost {
  files: [NewPostFile],
  caption: String,
}

type PostFile {
  type: String,
  uri: String,
}

type Post {
  _id: ID,
  user: User
  uid: ID,
  files: [PostFile],
  caption: String,
  likes: Int,
  comments: [String],
  createdDate: DateTime,
}

type UserPosts {
  user: User,
  posts: [Post],
}

extend type Mutation {
  createPost(form: NewPost): Boolean,
  deletePost(docId: ID): Boolean,
}

extend type Query {
  getPosts(startAt: ID): [Post],
  getUserPosts(uid: ID, startAt: ID): UserPosts,
}